# Site settings
author: Pablo Gonzalez
title: My Programming Journey
header-img: img/home-bg.png
email: pabgon0@gmail.com
copyright_name: Pablo Gonzalez
description: > # this means to ignore newlines until "baseurl:"
  Pablo Gonzalez
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Pabgon0

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
